---
- hosts: all
  remote_user: root
  become: true
  become_method: sudo

  tasks:
    - name: Install jq
      get_url:
        url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
        dest: /usr/local/bin/jq
        mode: 0755
